version: '3'
#export COMPOSE_CONVERT_WINDOWS_PATHS=1
#set COMPOSE_CONVERT_WINDOWS_PATHS=1
#export PATH=/opt/lampp/bin:$PATH
#docker exec -ti myXampp bash
#ssh root@localhost -p 41061
#docker exec <name container> /opt/lampp/lampp restart
#https://github.com/tomsik68/docker-xampp
#docker-compose down && Docker-compose up -d
#mysql
#CREATE DATABASE 'name'
#mysql -u -p <db-name> < <db-dump-path>
services:
  nginxproxy:
    restart: always
    image: jwilder/nginx-proxy
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
    - "80:80"

  web:
    environment:
      VIRTUAL_HOST: blah.localhost
    volumes:
    - C:\xampp\htdocs\<foldername>:/www
    build: .
    ports:
    - "41061:22"
    - "41062:80"
    image: "tomsik68/xampp"